#!/usr/bin/env python3
"""Combine per-style manifests under assets/anim/<style>/manifest.json into one
assets/anim/manifest.js the renderer can load under connect-src 'none'.

window.KRISHNA_ANIM_STYLES = { <style>: {...} } for every assets/anim/<style>/manifest.json
window.KRISHNA_ANIM = the default style's manifest (backward compatible)
Usage: assemble-manifest.py <assets/anim dir> <default style>
"""
import sys, os, json
root, default = sys.argv[1], sys.argv[2]
styles = {}
for name in sorted(os.listdir(root)):
    p = os.path.join(root, name, 'manifest.json')
    if os.path.isfile(p):
        m = json.load(open(p))
        # sheet paths are relative to assets/anim; make sure the prefix is present
        for seg in m['segments'].values():
            if '/' not in seg['file']:
                seg['file'] = f'{name}/{seg["file"]}'
        m['style'] = name
        styles[name] = m
assert default in styles, f'default style {default} missing'
combined = {'default': default, 'styles': styles}
json.dump(combined, open(os.path.join(root, 'manifest.json'), 'w'), indent=1)
with open(os.path.join(root, 'manifest.js'), 'w') as f:
    f.write('// Generated by scripts/anim/assemble-manifest.py from assets/anim/<style>/manifest.json; do not edit by hand.\n')
    f.write('window.KRISHNA_ANIM_STYLES = ' + json.dumps(styles, separators=(',', ':')) + ';\n')
    f.write(f'window.KRISHNA_ANIM_DEFAULT_STYLE = {json.dumps(default)};\n')
    f.write('window.KRISHNA_ANIM = window.KRISHNA_ANIM_STYLES[window.KRISHNA_ANIM_DEFAULT_STYLE];\n')
print('styles:', ', '.join(styles), '| default:', default, '|', os.path.getsize(os.path.join(root, 'manifest.js')) // 1024, 'KB manifest.js')
